version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_konecta
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: konecta
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend_konecta
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
